name: The Portable Tow Truck
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50295
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbf7f8'
    - '#500a03'
    - '#f56000'
    - '#ffad1f'
    - '#a18380'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
