favicon: null
name: The Portable Tow Truck
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 1
  brandStrength: 0.5021482
  lightness: 0
  brandColors:
    - '#fbf7f8'
    - '#500a03'
    - '#f56000'
    - '#ffad1f'
    - '#a18380'
  rhythmicContrast: 1
typography_spectrum: 0.50295
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.5128894
analytics:
  twitter: null
  google: null
  facebook: null
